### ISSUE TITLE
Caret

### ISSUE THREAD

**Issue by adamsanderson** [component/selection#2]
Just thought I'd let you know, I have a component, [caret](https://github.com/adamsanderson/caret) that handles _some_ of the tricky selection/caret issues.  

Anyways, it might be worth a peek if you run into anything odd, there are some horrific edge cases around rich text editing.

**Comment by tj** [comment]
ah! cool, didn't see that one

**Comment by TooTallNate** [comment]
There's also https://github.com/stagas/select
